server:
  port: ${PORT:8800}

spring:
  datasource:
    url: jdbc:h2:mem:library;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.H2Dialect

springdoc:
  show-actuator: true

